using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aiv.Fast2D.Utils.Input
{
    public enum AivKeyCode
    {
        // 0 from 200 is keyboard keys
        ShiftLeft = Input.KEYBOARD_OFFSET + 1,
        ShiftRight = 2,
        CtrlLeft = 3,
        CtrlRight = 4,
        F1 = 10,
        F2 = 11,
        F3 = 12,
        F4 = 13,
        F5 = 14,
        F6 = 15,
        F7 = 16,
        F8 = 17,
        F9 = 18,
        F10 = 19,
        Up = 45,
        Down = 46,
        Left = 47,
        Right = 48,
        Return = 49,
        Esc = 50,
        Space = 51,
        Tab = 52,
        Keypad0 = 67,
        Keypad1 = 68,
        Keypad2 = 69,
        Keypad3 = 70,
        Keypad4 = 71,
        Keypad5 = 72,
        Keypad6 = 73,
        Keypad7 = 74,
        Keypad8 = 75,
        Keypad9 = 76,
        A = 83,
        B = 84,
        C = 85,
        D = 86,
        E = 87,
        F = 88,
        G = 89,
        H = 90,
        I = 91,
        J = 92,
        K = 93,
        L = 94,
        M = 95,
        N = 96,
        O = 97,
        P = 98,
        Q = 99,
        R = 100,
        S = 101,
        T = 102,
        U = 103,
        V = 104,
        W = 105,
        X = 106,
        Y = 107,
        Z = 108,
        Num0 = 109,
        Num1 = 110,
        Num2 = 111,
        Num3 = 112,
        Num4 = 113,
        Num5 = 114,
        Num6 = 115,
        Num7 = 116,
        Num8 = 117,
        Num9 = 118,

        // 201 to 300 is mouse keys
        MouseLeft = Input.MOUSE_OFFSET + 1,
        MouseMiddle,
        MouseRight,
        MouseButton1,
        MouseButton2,
        MouseButton3,
        MouseButton4,
        MouseButton5,
        MouseButton6,
        MouseButton7,
        MouseButton8,

        // 301 to 400 is joystick 1 keys
        Joystick1ButtonA = Input.JOYPAD_OFFSET + 1,
        Joystick1ButtonB,
        Joystick1ButtonX,
        Joystick1ButtonY,
        Joystick1DpadUp,
        Joystick1DpadDown,
        Joystick1DpadLeft,
        Joystick1DpadRight,
        Joystick1Start,
        Joystick1Back,
        Joystick1BigButton,
        Joystick1BumperLeft,
        Joystick1BumperRight,
        Joystick1TriggerLeft,
        Joystick1TriggerRight,
        Joystick1StickRight,
        Joystick1StickLeft,

        // 401 to 500 is joystick 2 keys
        Joystick2ButtonA = Input.JOYPAD_OFFSET + 101,
        Joystick2ButtonB,
        Joystick2ButtonX,
        Joystick2ButtonY,
        Joystick2DpadUp,
        Joystick2DpadDown,
        Joystick2DpadLeft,
        Joystick2DpadRight,
        Joystick2Start,
        Joystick2Back,
        Joystick2BigButton,
        Joystick2BumperLeft,
        Joystick2BumperRight,
        Joystick2TriggerLeft,
        Joystick2TriggerRight,
        Joystick2StickRight,
        Joystick2StickLeft,

    }
}
